"""modify cleanup_events table event_status values

Revision ID: 1ef48c8b3921
Revises: d33b3fc6cd9f
Create Date: 2025-07-04 16:16:59.881417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ef48c8b3921'
down_revision: Union[str, None] = 'd33b3fc6cd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE cleanup_event_verification_enum ADD VALUE IF NOT EXISTS 'submitted'")

 
def downgrade() -> None:
    """Downgrade schema."""
    pass    
    # ### commands auto generated by Alembic - please adjust! ###
   