"""strip down users table to minimal signup schema

Revision ID: 417c9f6125a6
Revises: aa0b2d621dca
Create Date: 2025-06-12 11:46:28.813788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '417c9f6125a6'
down_revision: Union[str, None] = 'aa0b2d621dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'user_name',
        new_column_name='username',
        existing_type=sa.String(255),
        type_=sa.String(50),
        existing_nullable=True,
    )
    # (re)create an index on username for lookups
    op.create_index('ix_users_username', 'users', ['username'], unique=True)

    # 2) Drop now-unused columns
    for col in [
        'first_name', 'last_name',
        'phone', 'avatar',
        'referral_code',
        'created_by', 'updated_by'
    ]:
        op.drop_column('users', col)

    # 3) Ensure updated_at is non-nullable
    op.alter_column(
        'users', 'updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(255), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(20), nullable=True, unique=True))
    op.add_column('users', sa.Column('avatar', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer, sa.ForeignKey('users.id'), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer, sa.ForeignKey('users.id'), nullable=True))

    # 2) Drop the new username index
    op.drop_index('ix_users_username', table_name='users')

    # 3) Rename username → user_name and restore length
    op.alter_column(
        'users', 'username',
        new_column_name='user_name',
        existing_type=sa.String(50),
        type_=sa.String(255),
        existing_nullable=True,
    )

    # 4) Allow updated_at to be nullable again if that was original
    op.alter_column(
        'users', 'updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=True,
    )