"""fix event join model base

Revision ID: 9876d2d1562a
Revises: 57f2b5ae5405
Create Date: 2025-05-30 21:27:05.879350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9876d2d1562a'
down_revision: Union[str, None] = '57f2b5ae5405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
   op.drop_constraint('event_join_approved_by_fkey', 'event_join', type_='foreignkey')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'event_join_approved_by_fkey',
        'event_join',
        'users',
        ['approved_by'],
        ['id']
    )