"""add severity column in the litter group

Revision ID: aa0b2d621dca
Revises: 9876d2d1562a
Create Date: 2025-06-02 12:43:49.467062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa0b2d621dca'
down_revision: Union[str, None] = '9876d2d1562a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'litter_groups',
        sa.Column('severity', sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('litter_groups', 'severity')