"""modify litter report to add column city

Revision ID: e6703edb3f6b
Revises: 081dbbcd19da
Create Date: 2025-07-27 12:29:44.314957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6703edb3f6b'
down_revision: Union[str, None] = '081dbbcd19da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('litter_reports', sa.Column('city', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('litter_reports', 'city')